name: Pecm2Swift
options:
  bundleIdPrefix: com.pecm2
  deploymentTarget:
    iOS: 16.0
settings:
  base:
    SWIFT_VERSION: 5.9
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.25.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS.git
    from: 7.0.0

targets:
  Pecm2Swift:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - path: Pecm2Swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lilian.pecm2
        INFOPLIST_FILE: Pecm2Swift/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: MyTalk
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseFirestoreSwift
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
